# Test goal: Clang-CUDA build
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   GPU: Clang CUDA
#   HW: NVIDIA GPU
#   Scope: configure, build, unit tests, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Build type: RelWithDebInfo
#   Compiler: Clang 11
#   MPI: thread_MPI
#   GPU: Clang CUDA 11.4, CUDA 11.4
#   SIMD: AVX2_256, no kernels
#   FFT: FFTW3
#   Parallelism nt/ntomp: 4/2 (unit tests)
#   Parallelism nt/ntomp: 2/1 (regression tests)

gromacs:clang-11-cuda-11.4:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
    - .use-cuda
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-11-cuda-11.4.0-hipsycl-0bf6420aab18-rocm-4.2
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_USE_SIMD_KERNELS=off"
    CMAKE_EXTRA_OPTIONS: "-DGMX_CLANG_CUDA=ON"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
    COMPILER_MAJOR_VERSION: 11

gromacs:clang-11-cuda-11.4:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .use-clang:base
    - .use-ccache
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-11-cuda-11.4.0-hipsycl-0bf6420aab18-rocm-4.2
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
  needs:
    - job: gromacs:clang-11-cuda-11.4:configure

gromacs:clang-11-cuda-11.4:test:
  extends:
    - .gromacs:base:test
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-11-cuda-11.4.0-hipsycl-0bf6420aab18-rocm-4.2
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 1
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:clang-11-cuda-11.4:build

gromacs:clang-11-cuda-11.4:regressiontest:
  extends:
    - .gromacs:base:regressiontest
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-11-cuda-11.4.0-hipsycl-0bf6420aab18-rocm-4.2
  variables:
    CMAKE: /usr/local/cmake-3.17.2/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 1
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 2
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:clang-11-cuda-11.4:build
    - job: regressiontests:prepare