[build-system]
requires = ['cmake>=3.13',
            'pybind11>=2.6',
            'scikit-build>=0.10',
            'setuptools>=42',
            'wheel']
build-backend = 'setuptools.build_meta:__legacy__'
