# Test goal: Continuous integration testing for gmxapi 0.3 and client Python package.
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu oldest supported
#   GPU: unspecified
#   GROMACS: newest supported
#   gmxapi: gmxapi 0.3
#   Scope: build, install, test
# Test implementation choices (free to change as needed):
#   GROMACS branch: master
#   gmxapi Python package: 0.3 alpha from GROMACS master
#   compiler: clang-8


.gmxapi-0.3:clang-8:gmx2022:
  extends:
    - .variables:default
    - .use-clang:base
  image: ${CI_REGISTRY_IMAGE}/ci-ubuntu-20.04-llvm-8-cuda-11.0
  stage: test
  variables:
    KUBERNETES_CPU_LIMIT: 2
    KUBERNETES_CPU_REQUEST: 2
    KUBERNETES_MEMORY_LIMIT: 2Gi
    KUBERNETES_MEMORY_REQUEST: 2Gi
    PY_UNIT_TEST_XML: $CI_PROJECT_DIR/py-JUnitTestResults.xml
    PY_MPI_UNIT_TEST_XML: $CI_PROJECT_DIR/py-mpi-JUnitTestResults.xml
    PY_ACCEPTANCE_TEST_XML: $CI_PROJECT_DIR/gmxapi-acceptance-JUnitTestResults.xml
    PY_MPI_ACCEPTANCE_TEST_XML: $CI_PROJECT_DIR/gmxapi-acceptance-mpi-JUnitTestResults.xml
  script:
    - source $INSTALL_DIR/bin/GMXRC
    - source $VENVPATH/bin/activate
    - INSTALL_DIR=$PWD/$INSTALL_DIR OMP_NUM_THREADS=1 bash -x admin/ci-scripts/build-and-test-py-gmxapi-0.3.sh
  artifacts:
    reports:
      junit:
        - $PY_UNIT_TEST_XML
        - $PY_MPI_UNIT_TEST_XML
        - $PY_ACCEPTANCE_TEST_XML
        - $PY_MPI_ACCEPTANCE_TEST_XML
    paths:
      - dist/
    when: always
    expire_in: 1 week
  tags:
    - k8s-scilifelab
  # The dependency means we need to use the same tag restriction as upstream.
  needs:
    - job: gromacs:clang-8:build
      artifacts: true

gmxapi-0.3:clang-8:gmx2022:py-3.7.7:
  extends:
    - .gmxapi-0.3:clang-8:gmx2022
    - .rules:merge-requests:master
  variables:
    VENVPATH: "/root/venv/py3.7"
    PY_VER: "3.7.7"

gmxapi-0.3:clang-8:gmx2022:py-3.8.2:
  extends:
    - .gmxapi-0.3:clang-8:gmx2022
    - .rules:merge-requests:master
  variables:
    VENVPATH: "/root/venv/py3.8"
    PY_VER: "3.8.2"

gmxapi-0.3:clang-8:gmx2022:py-3.9.1:
  extends:
    - .gmxapi-0.3:clang-8:gmx2022
    - .rules:merge-requests:master
  variables:
    VENVPATH: "/root/venv/py3.9"
    PY_VER: "3.9.1"
